version: '3'
services:

  strazh:
    build: .
    image: strazh:dev
    container_name: strazh
    network_mode: host
    volumes:
      - C:\src\agoda-front-end\cronos\framework\src\Agoda.Cronos.Bootstrap:/dest1
      - C:\src\agoda-front-end\cronos\framework\src\Tests\Agoda.Cronos.BootstrapUnitTests:/dest2
    environment:
      - c=neo4j:neo4j:strazh
      - p=/dest1/Agoda.Cronos.Bootstrap.csproj /dest2/Agoda.Cronos.BootstrapUnitTests.csproj
