version: '3'
services:

  strazh:
    build: .
    image: strazh:dev
    container_name: strazh
    network_mode: host
    volumes:
      - C:\src\github\strazh\SystemUnderTest\Strazh.Tests.ProjectA:/dest1
      - C:\src\github\strazh\SystemUnderTest\Strazh.Tests.ProjectB:/dest2
    environment:
      - c=neo4j:neo4j:strazh
      - p=/dest2/Strazh.Tests.ProjectB.csproj /dest1/Strazh.Tests.ProjectA.csproj
