version: '3'
services:

  strazh:
    build: .
    image: strazh:dev
    container_name: strazh
    network_mode: host
    volumes:
      - C:\src\github\strazh\SystemUnderTest:/dest
    environment:
      - c=neo4j:neo4j:strazh
      - p=/dest/Strazh.Tests.ProjectB/Strazh.Tests.ProjectB.csproj /dest/Strazh.Tests.ProjectA/Strazh.Tests.ProjectA.csproj
