version: '3'
services:

  strazh:
    build: .
    image: strazh:dev
    container_name: strazh
    network_mode: host
    volumes:
      - C:\src\agoda-front-end\cronos\framework\src\Agoda.Cronos.Bootstrap:/dest
    environment:
      - c=neo4j:neo4j:strazh
      - p=/dest/Agoda.Cronos.Bootstrap.csproj
      - m=all
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:4.2.0
    container_name: strazh_neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/strazh
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms.memory.heap.initial_size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
