name: Publish Strazh Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Strazh Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          repository: vladbatushkov/strazh
          tag_with_ref: true